name: Auto Labeling

on:
  pull_request:
    types: [ opened, edited, synchronize, ready_for_review ]
   

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1
